#!/usr/bin/env python3
"""Regenerate org.telegram.messenger.ResLottieMeta from raw Lottie JSON.

NixgramX commits the generated class instead of Telegram's buildSrc
org.telegram.lottie-meta plugin (AGP 9 / kotlin-dsl friction on Gradle 9).

Usage (repo root):
  python3 tools/generate_res_lottie_meta.py
"""
from __future__ import annotations

import gzip
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "TMessagesProj/src/main/res"
OUT = ROOT / "TMessagesProj/src/main/java/org/telegram/messenger/ResLottieMeta.java"
MONO_SRC = ROOT / "TMessagesProj/src/main/java/org/telegram/messenger/MonoColorLottieList.java"


def mono_names() -> set[str]:
    text = MONO_SRC.read_text(encoding="utf-8")
    return set(re.findall(r"R\.raw\.([A-Za-z0-9_]+)", text))


def parse_lottie(path: Path):
    data = path.read_bytes()
    try:
        if data[:2] == b"\x1f\x8b":
            data = gzip.decompress(data)
        obj = json.loads(data.decode("utf-8"))
    except Exception:
        return None
    if not isinstance(obj, dict):
        return None
    fr, ip, op = obj.get("fr"), obj.get("ip"), obj.get("op")
    if fr is None or ip is None or op is None:
        return None
    try:
        fr, ip, op = float(fr), float(ip), float(op)
    except Exception:
        return None
    if fr <= 0:
        return None
    return fr, int(round(op - ip))


def main() -> int:
    mono = mono_names()
    files = [f for d in RES.glob("raw*") if d.is_dir() for f in d.glob("**/*.json")]
    parsed: dict[str, list[tuple[float, int, bool]]] = {}
    for f in files:
        info = parse_lottie(f)
        if not info:
            continue
        fps, frames = info
        name = f.stem
        parsed.setdefault(name, []).append((fps, frames, name in mono))

    entries = []
    for name in sorted(parsed):
        fps_raw, frame_count, is_mono = parsed[name][0]
        fps = int(round(fps_raw))
        if not (0 <= fps <= 0xFF and 0 <= frame_count <= 0x7FFFFF):
            raise SystemExit(f"overflow for {name}: fps={fps} frames={frame_count}")
        entries.append((name, fps, frame_count, is_mono))

    lines = [
        "package org.telegram.messenger;",
        "",
        "import androidx.annotation.RawRes;",
        "import java.util.Arrays;",
        "",
        "/** Generated by tools/generate_res_lottie_meta.py (Telegram 12.10.1 layout). Do not edit. */",
        "public final class ResLottieMeta {",
        "",
        "    // Packed long layout:",
        "    //   bits 63..32 (32) : R.raw resource id",
        "    //   bits 31..24 ( 8) : fps",
        "    //   bit  23     ( 1) : monocolor",
        "    //   bits 22.. 0 (23) : frame count",
        "    public static final long NOT_FOUND = -1L;",
        "",
        "    private ResLottieMeta() {",
        "    }",
        "",
        "    private static final class Holder {",
        "        private static final long[] DATA = build();",
        "    }",
        "",
        "    private static long[] build() {",
        "        final long[] data = new long[]{",
    ]
    for name, fps, frames, is_mono in entries:
        lines.append(f"            pack(R.raw.{name}, {fps}, {frames}, {str(is_mono).lower()}),")
    lines += [
        "        };",
        "        Arrays.sort(data); // sorts by resId (high 32 bits)",
        "        return data;",
        "    }",
        "",
        "    private static long pack(int resId, int fps, int frameCount, boolean mono) {",
        "        return ((long) resId << 32)",
        "                | ((long) (fps & 0xFF) << 24)",
        "                | (mono ? (1L << 23) : 0L)",
        "                | (frameCount & 0x7FFFFF);",
        "    }",
        "",
        "    /** @return packed metadata for resId, or {@link #NOT_FOUND}. */",
        "    public static long find(@RawRes int resId) {",
        "        final long[] data = Holder.DATA;",
        "        int lo = 0, hi = data.length - 1;",
        "        while (lo <= hi) {",
        "            final int mid = (lo + hi) >>> 1;",
        "            final int midId = (int) (data[mid] >>> 32);",
        "            if (midId < resId) {",
        "                lo = mid + 1;",
        "            } else if (midId > resId) {",
        "                hi = mid - 1;",
        "            } else {",
        "                return data[mid];",
        "            }",
        "        }",
        "        return NOT_FOUND;",
        "    }",
        "",
        "    public static boolean isLottie(@RawRes int resId) {",
        "        return find(resId) != NOT_FOUND;",
        "    }",
        "",
        "    /** Drop-in replacement for the old MonoColorLottieList.isMonoColorLottie(resId). */",
        "    public static boolean isMonoColor(@RawRes int resId) {",
        "        long packed = find(resId);",
        "        return packed != NOT_FOUND && isMonoColorOf(packed);",
        "    }",
        "",
        "    public static int fpsOf(long packed) {",
        "        return (int) ((packed >>> 24) & 0xFF);",
        "    }",
        "",
        "    public static boolean isMonoColorOf(long packed) {",
        "        return (packed & (1L << 23)) != 0L;",
        "    }",
        "",
        "    public static int frameCountOf(long packed) {",
        "        return (int) (packed & 0x7FFFFF);",
        "    }",
        "",
        "    public static int resIdOf(long packed) {",
        "        return (int) (packed >>> 32);",
        "    }",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(entries)} entries, {sum(1 for e in entries if e[3])} mono)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
